# This is a basic workflow to help you get started with Actions

name: Automatiska tester när  S4-IntegrationTestRabbit pushas.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - S4-IntegrationTestRabbit

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: hibernate
          MYSQL_PASSWORD: admin
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_hibernate
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
  #  env:
   #   DB_DATABASE: db_hibernate
    #  DB_USER: hibernate@127.0.0.1
     # DB_PASSWORD: admin  
   #  Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      - uses: actions/checkout@v1
      - run: mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e 'create database if not exists db_hibernate; create user hibernate@localhost IDENTIFIED BY admin; GRANT ALL PRIVILEGES ON * . * TO hibernate@localhost;'
      #- name: Set up MySQL
       # run: |
        #  sudo /etc/init.d/mysql start
         # mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    #   Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
        

      - name: Get Java JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Java Version
        run: java -version
      - name: Build Jar and Run Tests
        run: mvn test
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
   
